# Use a Python version that supports annotations (3.7 or later)
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --upgrade -r requirements.txt

# Copy the server directory
COPY server server/

# Expose the port your application listens on
EXPOSE 5000

# Run the application
CMD ["python", "server/main.py"]
